/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.Cont_total;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JButton;
import vista.ventanas_ingresoMontos.Menu_creditoauto;
import vista.ventanas_ingresoMontos.Menu_efectivo;
import vista.ventanas_ingresoMontos.Menu_sodexo;
import vista.ventanas_ingresoMontos.Menu_debitoauto;
import vista.ventanas_ingresoMontos.Menu_arcor;
import vista.ventanas_ingresoMontos.Menu_creditomult;
import vista.ventanas_ingresoMontos.Menu_hites;
import vista.ventanas_ingresoMontos.Menu_debitomult;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.border.EmptyBorder;
import vista.ventanas_ingresoMontos.Menu_webpay;

/**
 *
 * @author ezioc
 */
public class Menu_principal extends javax.swing.JFrame {

    /**
     * Creates new form menu_principal
     */
     Menu_efectivo menu_efectivo = new Menu_efectivo(this);
     Menu_debitomult menu_debitomult = new Menu_debitomult(this);
     Menu_debitoauto menu_debitoauto = new Menu_debitoauto(this);
     Menu_sodexo menu_sodexo = new Menu_sodexo(this);
     Menu_creditomult menu_creditomult = new Menu_creditomult(this);
     Menu_creditoauto menu_creditoauto = new Menu_creditoauto(this);
     Menu_hites menu_hites = new Menu_hites(this);
     Menu_arcor menu_arcor = new Menu_arcor(this);
     Menu_webpay menu_webpay = new Menu_webpay(this);
     
     
    public Menu_principal() {
        
        initComponents();
        this.setLocationRelativeTo(null);
        Cont_total ct = new Cont_total(this);
        btn_total.addActionListener(ct);
        
        
        
        
        
        
    }

    public JTextField getTotal_efectivo() {
        return total_efectivo;
    }

    public JTextField getTotal_debitomulticaja() {
        return total_debitomulticaja;
    }

    public JTextField getTotal_debitoauto() {
        return total_debitoauto;
    }

    public JTextField getTotal_sodexo() {
        return total_sodexo;
    }

    public JTextField getTotal_creditomult() {
        return total_creditomult;
    }

    public JTextField getTotal_creditoauto() {
        return total_creditoauto;
    }

    public JTextField getTotal_hites() {
        return total_hites;
    }

    public JTextField getTotal_arcor() {
        return total_arcor;
    }

    public JButton getBtn_total() {
        return btn_total;
    }

    public JTextField getTxt_total() {
        return txt_total;
    }

    public JTextField getTotal_webpay() {
        return total_webpay;
    }
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Agregar_montoEfectivo = new javax.swing.JButton();
        total_efectivo = new javax.swing.JTextField();
        titulo_debitomult = new javax.swing.JLabel();
        titulo_efectivo = new javax.swing.JLabel();
        Agregar_montodebito_multicaja = new javax.swing.JButton();
        total_debitomulticaja = new javax.swing.JTextField();
        titulo_debitoauto = new javax.swing.JLabel();
        Agregar_montodebitoauto = new javax.swing.JButton();
        total_debitoauto = new javax.swing.JTextField();
        titulo_sodexo = new javax.swing.JLabel();
        Agregar_sodexo = new javax.swing.JButton();
        total_sodexo = new javax.swing.JTextField();
        titulo_creditomulticaja = new javax.swing.JLabel();
        Agregar_creditomult = new javax.swing.JButton();
        total_creditomult = new javax.swing.JTextField();
        titulo_creditoauto = new javax.swing.JLabel();
        Agregar_creditoauto = new javax.swing.JButton();
        total_creditoauto = new javax.swing.JTextField();
        titulo_hites = new javax.swing.JLabel();
        Agregar_hites = new javax.swing.JButton();
        total_hites = new javax.swing.JTextField();
        txt_total = new javax.swing.JTextField();
        btn_total = new javax.swing.JButton();
        titulo_arcor = new javax.swing.JLabel();
        Agregar_arcor = new javax.swing.JButton();
        total_arcor = new javax.swing.JTextField();
        titulo_webpay = new javax.swing.JLabel();
        Agregar_webpay = new javax.swing.JButton();
        total_webpay = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btn_guardar = new javax.swing.JButton();
        txt_dia = new javax.swing.JTextField();
        txt_mes = new javax.swing.JTextField();
        txt_año = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Agregar_montoEfectivo.setBackground(new java.awt.Color(0, 0, 0));
        Agregar_montoEfectivo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Agregar_montoEfectivo.setForeground(new java.awt.Color(255, 255, 255));
        Agregar_montoEfectivo.setText("Agregar");
        Agregar_montoEfectivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Agregar_montoEfectivoActionPerformed(evt);
            }
        });

        total_efectivo.setText("0");
        total_efectivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total_efectivoActionPerformed(evt);
            }
        });

        titulo_debitomult.setBackground(new java.awt.Color(102, 102, 102));
        titulo_debitomult.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        titulo_debitomult.setForeground(new java.awt.Color(255, 255, 255));
        titulo_debitomult.setText("  Debito-Multicaja");
        titulo_debitomult.setOpaque(true);

        titulo_efectivo.setBackground(new java.awt.Color(102, 102, 102));
        titulo_efectivo.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        titulo_efectivo.setForeground(new java.awt.Color(255, 255, 255));
        titulo_efectivo.setText("          Efectivo");
        titulo_efectivo.setOpaque(true);

        Agregar_montodebito_multicaja.setBackground(new java.awt.Color(0, 0, 0));
        Agregar_montodebito_multicaja.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Agregar_montodebito_multicaja.setForeground(new java.awt.Color(255, 255, 255));
        Agregar_montodebito_multicaja.setText("Agregar");
        Agregar_montodebito_multicaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Agregar_montodebito_multicajaActionPerformed(evt);
            }
        });

        total_debitomulticaja.setText("0");
        total_debitomulticaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total_debitomulticajaActionPerformed(evt);
            }
        });

        titulo_debitoauto.setBackground(new java.awt.Color(102, 102, 102));
        titulo_debitoauto.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        titulo_debitoauto.setForeground(new java.awt.Color(255, 255, 255));
        titulo_debitoauto.setText("Debito-Autoservicio");
        titulo_debitoauto.setOpaque(true);

        Agregar_montodebitoauto.setBackground(new java.awt.Color(0, 0, 0));
        Agregar_montodebitoauto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Agregar_montodebitoauto.setForeground(new java.awt.Color(255, 255, 255));
        Agregar_montodebitoauto.setText("Agregar");
        Agregar_montodebitoauto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Agregar_montodebitoautoActionPerformed(evt);
            }
        });

        total_debitoauto.setText("0");
        total_debitoauto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total_debitoautoActionPerformed(evt);
            }
        });

        titulo_sodexo.setBackground(new java.awt.Color(102, 102, 102));
        titulo_sodexo.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        titulo_sodexo.setForeground(new java.awt.Color(255, 255, 255));
        titulo_sodexo.setText("            Sodexo");
        titulo_sodexo.setOpaque(true);

        Agregar_sodexo.setBackground(new java.awt.Color(0, 0, 0));
        Agregar_sodexo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Agregar_sodexo.setForeground(new java.awt.Color(255, 255, 255));
        Agregar_sodexo.setText("Agregar");
        Agregar_sodexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Agregar_sodexoActionPerformed(evt);
            }
        });

        total_sodexo.setText("0");
        total_sodexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total_sodexoActionPerformed(evt);
            }
        });

        titulo_creditomulticaja.setBackground(new java.awt.Color(102, 102, 102));
        titulo_creditomulticaja.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        titulo_creditomulticaja.setForeground(new java.awt.Color(255, 255, 255));
        titulo_creditomulticaja.setText("  Credito-Multicaja");
        titulo_creditomulticaja.setOpaque(true);

        Agregar_creditomult.setBackground(new java.awt.Color(0, 0, 0));
        Agregar_creditomult.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Agregar_creditomult.setForeground(new java.awt.Color(255, 255, 255));
        Agregar_creditomult.setText("Agregar");
        Agregar_creditomult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Agregar_creditomultActionPerformed(evt);
            }
        });

        total_creditomult.setText("0");
        total_creditomult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total_creditomultActionPerformed(evt);
            }
        });

        titulo_creditoauto.setBackground(new java.awt.Color(102, 102, 102));
        titulo_creditoauto.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        titulo_creditoauto.setForeground(new java.awt.Color(255, 255, 255));
        titulo_creditoauto.setText(" Credito-AutoServicio");
        titulo_creditoauto.setOpaque(true);

        Agregar_creditoauto.setBackground(new java.awt.Color(0, 0, 0));
        Agregar_creditoauto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Agregar_creditoauto.setForeground(new java.awt.Color(255, 255, 255));
        Agregar_creditoauto.setText("Agregar");
        Agregar_creditoauto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Agregar_creditoautoActionPerformed(evt);
            }
        });

        total_creditoauto.setText("0");
        total_creditoauto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total_creditoautoActionPerformed(evt);
            }
        });

        titulo_hites.setBackground(new java.awt.Color(102, 102, 102));
        titulo_hites.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        titulo_hites.setForeground(new java.awt.Color(255, 255, 255));
        titulo_hites.setText("              Hites");
        titulo_hites.setOpaque(true);

        Agregar_hites.setBackground(new java.awt.Color(0, 0, 0));
        Agregar_hites.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Agregar_hites.setForeground(new java.awt.Color(255, 255, 255));
        Agregar_hites.setText("Agregar");
        Agregar_hites.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Agregar_hitesActionPerformed(evt);
            }
        });

        total_hites.setText("0");
        total_hites.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total_hitesActionPerformed(evt);
            }
        });

        btn_total.setBackground(new java.awt.Color(153, 153, 153));
        btn_total.setForeground(new java.awt.Color(0, 0, 0));
        btn_total.setText("Calcular Total");

        titulo_arcor.setBackground(new java.awt.Color(102, 102, 102));
        titulo_arcor.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        titulo_arcor.setForeground(new java.awt.Color(255, 255, 255));
        titulo_arcor.setText("              Arcor");
        titulo_arcor.setOpaque(true);

        Agregar_arcor.setBackground(new java.awt.Color(0, 0, 0));
        Agregar_arcor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Agregar_arcor.setForeground(new java.awt.Color(255, 255, 255));
        Agregar_arcor.setText("Agregar");
        Agregar_arcor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Agregar_arcorActionPerformed(evt);
            }
        });

        total_arcor.setText("0");
        total_arcor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total_arcorActionPerformed(evt);
            }
        });

        titulo_webpay.setBackground(new java.awt.Color(102, 102, 102));
        titulo_webpay.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        titulo_webpay.setForeground(new java.awt.Color(255, 255, 255));
        titulo_webpay.setText("            Webpay");
        titulo_webpay.setOpaque(true);

        Agregar_webpay.setBackground(new java.awt.Color(0, 0, 0));
        Agregar_webpay.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Agregar_webpay.setForeground(new java.awt.Color(255, 255, 255));
        Agregar_webpay.setText("Agregar");
        Agregar_webpay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Agregar_webpayActionPerformed(evt);
            }
        });

        total_webpay.setText("0");
        total_webpay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total_webpayActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/descarga.png"))); // NOI18N

        btn_guardar.setText("Guardar");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        txt_dia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_diaKeyTyped(evt);
            }
        });

        txt_mes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_mesKeyTyped(evt);
            }
        });

        txt_año.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_añoKeyTyped(evt);
            }
        });

        jLabel2.setText("/");

        jLabel3.setText("/");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Fecha");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(titulo_debitomult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(titulo_efectivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(titulo_debitoauto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(titulo_sodexo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(titulo_creditomulticaja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(titulo_creditoauto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(titulo_hites, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Agregar_montoEfectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(total_efectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Agregar_montodebito_multicaja, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(total_debitomulticaja, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Agregar_montodebitoauto, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(total_debitoauto, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Agregar_sodexo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(total_sodexo, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Agregar_creditomult, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(total_creditomult, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Agregar_creditoauto, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(total_creditoauto, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Agregar_hites, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(total_hites, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_total)
                                .addGap(24, 24, 24)
                                .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(titulo_arcor, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(Agregar_arcor, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(total_arcor, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(titulo_webpay, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(Agregar_webpay, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(total_webpay, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_dia, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_mes, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_año, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_guardar)))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(total_efectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titulo_efectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Agregar_montoEfectivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titulo_debitomult, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Agregar_montodebito_multicaja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(total_debitomulticaja, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titulo_debitoauto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Agregar_montodebitoauto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(total_debitoauto, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(titulo_sodexo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Agregar_sodexo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(titulo_creditomulticaja, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Agregar_creditomult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(titulo_creditoauto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Agregar_creditoauto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(total_creditoauto, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Agregar_hites)
                                .addComponent(total_hites, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(titulo_hites, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(total_sodexo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(total_creditomult, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titulo_arcor, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Agregar_arcor)
                    .addComponent(total_arcor, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titulo_webpay, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Agregar_webpay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(total_webpay, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_total)
                    .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_guardar)
                    .addComponent(txt_dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_año, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Agregar_montoEfectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Agregar_montoEfectivoActionPerformed
       menu_efectivo.setVisible(true);
    }//GEN-LAST:event_Agregar_montoEfectivoActionPerformed

    private void total_efectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total_efectivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_total_efectivoActionPerformed

    private void Agregar_montodebito_multicajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Agregar_montodebito_multicajaActionPerformed
        // TODO add your handling code here:
        menu_debitomult.setVisible(true);
    }//GEN-LAST:event_Agregar_montodebito_multicajaActionPerformed

    private void total_debitomulticajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total_debitomulticajaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_total_debitomulticajaActionPerformed

    private void Agregar_montodebitoautoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Agregar_montodebitoautoActionPerformed
        // TODO add your handling code here:
        menu_debitoauto.setVisible(true);
    }//GEN-LAST:event_Agregar_montodebitoautoActionPerformed

    private void total_debitoautoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total_debitoautoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_total_debitoautoActionPerformed

    private void Agregar_sodexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Agregar_sodexoActionPerformed
        // TODO add your handling code here:
        menu_sodexo.setVisible(true);
    }//GEN-LAST:event_Agregar_sodexoActionPerformed

    private void total_sodexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total_sodexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_total_sodexoActionPerformed

    private void Agregar_creditomultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Agregar_creditomultActionPerformed
        // TODO add your handling code here:
        menu_creditomult.setVisible(true);
    }//GEN-LAST:event_Agregar_creditomultActionPerformed

    private void total_creditomultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total_creditomultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_total_creditomultActionPerformed

    private void Agregar_creditoautoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Agregar_creditoautoActionPerformed
        // TODO add your handling code here:
        menu_creditoauto.setVisible(true);
    }//GEN-LAST:event_Agregar_creditoautoActionPerformed

    private void total_creditoautoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total_creditoautoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_total_creditoautoActionPerformed

    private void Agregar_hitesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Agregar_hitesActionPerformed
        // TODO add your handling code here:
        menu_hites.setVisible(true);
    }//GEN-LAST:event_Agregar_hitesActionPerformed

    private void total_hitesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total_hitesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_total_hitesActionPerformed

    private void Agregar_arcorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Agregar_arcorActionPerformed
        // TODO add your handling code here:
        menu_arcor.setVisible(true);
    }//GEN-LAST:event_Agregar_arcorActionPerformed

    private void total_arcorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total_arcorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_total_arcorActionPerformed

    private void Agregar_webpayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Agregar_webpayActionPerformed
        // TODO add your handling code here:
        menu_webpay.setVisible(true);
    }//GEN-LAST:event_Agregar_webpayActionPerformed

    private void total_webpayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total_webpayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_total_webpayActionPerformed

    private void txt_diaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_diaKeyTyped
        // TODO add your handling code here:
        if(txt_dia.getText().length() >= 2){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_txt_diaKeyTyped

    private void txt_mesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_mesKeyTyped
        // TODO add your handling code here:
        if(txt_mes.getText().length() >= 2){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_txt_mesKeyTyped

    private void txt_añoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_añoKeyTyped
        // TODO add your handling code here:
        if(txt_año.getText().length() >= 4){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_txt_añoKeyTyped

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        // TODO add your handling code here:
        try{
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/bd_pjarqueo","root","");
            PreparedStatement pst = cn.prepareStatement("insert into registros values(?,?,?,?,?,?,?,?,?,?,?)");
        if(txt_dia.getText().equals("")){
            JOptionPane.showMessageDialog(null,"ERROR, NO SE HA INGRESADO EL DIA    ");
        }
        if(txt_mes.getText().equals("")){
            JOptionPane.showMessageDialog(null,"ERROR, NO SE HA INGRESADO EL MES    ");
        }
        if(txt_año.getText().equals("")){
            JOptionPane.showMessageDialog(null,"ERROR, NO SE HA INGRESADO EL AÑO   ");
        }else{
        String dia = txt_dia.getText();
        String mes = txt_mes.getText();
        String año = txt_año.getText();
        if(dia.length() == 1){
            dia = "0"+dia;
        }
        if(mes.length() == 1){
            mes = "0"+mes;
        }
        if(año.length() < 4){
            JOptionPane.showMessageDialog(null,"ERROR,INGRESE EL AÑO CORRECTAMENTE");
        }else{
        String fecha = dia+"/"+mes+"/"+año;
        String [] arreglo = {"Si","No"};
        int opcion = JOptionPane.showOptionDialog(null, "Esta seguro de querer guardar con fecha "+fecha+" ?", "Advertencia", 0, JOptionPane.QUESTION_MESSAGE,null, arreglo, "");
        if(opcion == 0){
            //System.out.println("si"); 
            pst.setString(1,fecha.trim());
            pst.setString(2, this.getTotal_efectivo().getText().trim());
            pst.setString(3, this.getTotal_sodexo().getText().trim());
            pst.setString(4, this.getTotal_debitomulticaja().getText().trim());
            pst.setString(5, this.getTotal_debitoauto().getText().trim());
            pst.setString(6, this.getTotal_creditomult().getText().trim());
            pst.setString(7, this.getTotal_creditoauto().getText().trim());
            pst.setString(8, this.getTotal_hites().getText().trim());
            pst.setString(9, this.getTotal_arcor().getText().trim());
            pst.setString(10, this.getTotal_webpay().getText().trim());
            pst.setString(11, this.getTxt_total().getText().trim());
            pst.executeUpdate();
            
        }
        if(opcion == 1){
            //System.out.println("no");
        }
        }
        }
        }catch(SQLException e){
            System.out.println(e.getMessage());
                 
        }
    }//GEN-LAST:event_btn_guardarActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar_arcor;
    private javax.swing.JButton Agregar_creditoauto;
    private javax.swing.JButton Agregar_creditomult;
    private javax.swing.JButton Agregar_hites;
    private javax.swing.JButton Agregar_montoEfectivo;
    private javax.swing.JButton Agregar_montodebito_multicaja;
    private javax.swing.JButton Agregar_montodebitoauto;
    private javax.swing.JButton Agregar_sodexo;
    private javax.swing.JButton Agregar_webpay;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_total;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel titulo_arcor;
    private javax.swing.JLabel titulo_creditoauto;
    private javax.swing.JLabel titulo_creditomulticaja;
    private javax.swing.JLabel titulo_debitoauto;
    private javax.swing.JLabel titulo_debitomult;
    private javax.swing.JLabel titulo_efectivo;
    private javax.swing.JLabel titulo_hites;
    private javax.swing.JLabel titulo_sodexo;
    private javax.swing.JLabel titulo_webpay;
    private javax.swing.JTextField total_arcor;
    private javax.swing.JTextField total_creditoauto;
    private javax.swing.JTextField total_creditomult;
    private javax.swing.JTextField total_debitoauto;
    private javax.swing.JTextField total_debitomulticaja;
    private javax.swing.JTextField total_efectivo;
    private javax.swing.JTextField total_hites;
    private javax.swing.JTextField total_sodexo;
    private javax.swing.JTextField total_webpay;
    private javax.swing.JTextField txt_año;
    private javax.swing.JTextField txt_dia;
    private javax.swing.JTextField txt_mes;
    private javax.swing.JTextField txt_total;
    // End of variables declaration//GEN-END:variables
}
